/* This file is generated by code_gen.py */
#ifndef __SCHEMA_H__
#define __SCHEMA_H__

	struct lineitem {
		int l_orderkey;
		int l_partkey;
		int l_suppkey;
		int l_linenumber;
		int l_quantity;
		float l_extendedprice;
		float l_discount;
		float l_tax;
		int l_returnflag;
		int l_linestatus;
		int l_shipdate;
		char l_commitdate[10];
		char l_receiptdate[10];
		char l_shipinstruct[17];
		char l_shipmode[7];
		char l_comment[43];
	};

	struct orders {
		int o_orderkey;
		int o_custkey;
		char o_orderstatus[1];
		float o_totalprice;
		int o_orderdate;
		char o_orderpriority[15];
		char o_clerk[15];
		int o_shippriority;
		char o_comment[78];
	};

	struct customer {
		int c_custkey;
		char c_name[18];
		char c_address[40];
		int c_nationkey;
		char c_phone[15];
		float c_acctbal;
		int c_mktsegment;
		char c_comment[116];
	};

	struct part {
		int p_partkey;
		char p_name[54];
		int p_mfgr;
		char p_brand[8];
		int p_type;
		int p_size;
		char p_container[10];
		float p_retailprice;
		char p_comment[22];
	};

	struct partsupp {
		int ps_partkey;
		int ps_suppkey;
		int ps_availqty;
		int ps_supplycost;
		char ps_comment[198];
	};

	struct supplier {
		int s_suppkey;
		int s_name;
		char s_address[40];
		int s_nationkey;
		char s_phone[12];
		float s_acctbal;
		char s_comment[100];
	};

	struct nation {
		int n_nationkey;
		int n_name;
		int n_regionkey;
		char n_comment[114];
	};

	struct region {
		int r_regionkey;
		int r_name;
		char r_comment[115];
	};

#endif
